from flask import Flask, request # type: ignore
from flask_cors import CORS # type: ignore
from models import db, create_tables
import queries
import json

app = Flask(__name__)
CORS(app)


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    db.connect()

# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not db.is_closed():
        db.close()


@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"



@app.get("/api/orders/top_5")
def api_orders_top5():
    rv = queries.get_last_n_orders(5)
    return json.dumps(rv)

@app.get("/api/artists/top_5")
def api_artists_top5():
    rv = queries.get_top_n_artists(5)
    return json.dumps(rv)

@app.route("/api/artists", methods=['PUT'])
def api_artists_put():
    new_artist = request.json
    q = queries.new_artist(new_artist)
    if q:
        return "Ok"
    return "Not OK"


#@app.get("/")

